/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import com.motorph.payrollsystem.AttendanceTracking.Attendance;
import com.motorph.payrollsystem.LeaveManagement.LeaveFrame;
import com.motorph.payrollsystem.EmployeeManagement.ViewRecordFrame;
import com.motorph.payrollsystem.EmployeeManagement.AddEmployeeFrame;
import com.motorph.payrollsystem.EmployeeManagement.DeleteRecordFrame;
import com.motorph.payrollsystem.PayrollCalculation.PayslipFrame;
import com.motorph.payrollsystem.UserManagement.LogInFrame;
import com.motorph.payrollsystem.EmployeeManagement.Employees;
import com.opencsv.CSVReader;
import com.opencsv.exceptions.CsvValidationException;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author trishamei
 */
public class MainFrame extends javax.swing.JDialog {

    /**
     * Creates new form MainFrame
     * @throws java.io.IOException
     * @throws java.io.FileNotFoundException
     * @throws com.opencsv.exceptions.CsvValidationException
     */
    public MainFrame() throws IOException, FileNotFoundException, CsvValidationException {
        initComponents();
        this.setModalityType(ModalityType.APPLICATION_MODAL);
        
        Employees employees = new Employees();     
        table1.setModel(employees.tableDetails("MotorPH Employee Data.csv"));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        Attendance = new javax.swing.JButton();
        exitbtn1 = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        payslipbtn = new javax.swing.JButton();
        leavebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        viewbtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        table1.setForeground(new java.awt.Color(51, 51, 51));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Employee No.", "Last Name", "First Name", "Birthday"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table1.setSelectionBackground(new java.awt.Color(102, 102, 102));
        table1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        table1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(table1);
        if (table1.getColumnModel().getColumnCount() > 0) {
            table1.getColumnModel().getColumn(0).setPreferredWidth(100);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 860, 280));

        Attendance.setBackground(new java.awt.Color(249, 182, 17));
        Attendance.setFont(new java.awt.Font("Thonburi", 1, 12)); // NOI18N
        Attendance.setForeground(new java.awt.Color(255, 255, 255));
        Attendance.setText("Attendance Record");
        Attendance.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Attendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AttendanceMouseClicked(evt);
            }
        });
        Attendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttendanceActionPerformed(evt);
            }
        });
        jPanel2.add(Attendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, 170, 30));

        exitbtn1.setBackground(new java.awt.Color(204, 51, 0));
        exitbtn1.setFont(new java.awt.Font("Thonburi", 1, 12)); // NOI18N
        exitbtn1.setForeground(new java.awt.Color(255, 255, 255));
        exitbtn1.setText("X");
        exitbtn1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        exitbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitbtn1MouseClicked(evt);
            }
        });
        exitbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(exitbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 25, 20, 20));

        addbtn.setBackground(new java.awt.Color(249, 182, 17));
        addbtn.setFont(new java.awt.Font("Thonburi", 1, 12)); // NOI18N
        addbtn.setForeground(new java.awt.Color(255, 255, 255));
        addbtn.setText("Add Record");
        addbtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddEmployee(evt);
            }
        });
        jPanel2.add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 170, 30));

        payslipbtn.setBackground(new java.awt.Color(249, 182, 17));
        payslipbtn.setFont(new java.awt.Font("Thonburi", 1, 12)); // NOI18N
        payslipbtn.setForeground(new java.awt.Color(255, 255, 255));
        payslipbtn.setText("Generate Payslip");
        payslipbtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        payslipbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaySlip(evt);
            }
        });
        payslipbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payslipbtnActionPerformed(evt);
            }
        });
        jPanel2.add(payslipbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, 170, 30));

        leavebtn.setBackground(new java.awt.Color(249, 182, 17));
        leavebtn.setFont(new java.awt.Font("Thonburi", 1, 12)); // NOI18N
        leavebtn.setForeground(new java.awt.Color(255, 255, 255));
        leavebtn.setText("Manage Leave");
        leavebtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        leavebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leavebtnMouseClicked(evt);
            }
        });
        leavebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leavebtnActionPerformed(evt);
            }
        });
        jPanel2.add(leavebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 170, 30));

        deletebtn.setBackground(new java.awt.Color(249, 182, 17));
        deletebtn.setFont(new java.awt.Font("Thonburi", 1, 12)); // NOI18N
        deletebtn.setForeground(new java.awt.Color(255, 255, 255));
        deletebtn.setText("Delete Record");
        deletebtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        deletebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteRecord(evt);
            }
        });
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        jPanel2.add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 530, 170, 30));

        viewbtn1.setBackground(new java.awt.Color(249, 182, 17));
        viewbtn1.setFont(new java.awt.Font("Thonburi", 1, 12)); // NOI18N
        viewbtn1.setForeground(new java.awt.Color(255, 255, 255));
        viewbtn1.setText("View and Update Record");
        viewbtn1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        viewbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewbtn1MouseClicked(evt);
            }
        });
        viewbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(viewbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 170, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/trishameiatienza/Downloads/MotorPH Payroll System Program/src/main/java/Frames/Manage Employee Information.png")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteRecord(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteRecord
        Employees employees = new Employees();

        try{
            String en = table1.getModel().getValueAt(table1.getSelectedRow(), 0).toString();

            employees.setemployeenum(table1.getModel().getValueAt(table1.getSelectedRow(), 0).toString());
            employees.setlastname(table1.getModel().getValueAt(table1.getSelectedRow(), 1).toString());
            employees.setfirstname(table1.getModel().getValueAt(table1.getSelectedRow(), 2).toString());
            employees.setsss(table1.getModel().getValueAt(table1.getSelectedRow(),3).toString());
            employees.setphilhealth(table1.getModel().getValueAt(table1.getSelectedRow(), 4).toString());
            employees.settax(table1.getModel().getValueAt(table1.getSelectedRow(), 5).toString());
            employees.setpagibig(table1.getModel().getValueAt(table1.getSelectedRow(), 6).toString());

            String filename = "MotorPH Employee Data.csv";
            try {
                CSVReader csvreader = new CSVReader(new FileReader(filename));
                String[] line;

                while((line=csvreader.readNext())!=null){
                    if(line[0].equals(en)){
                        employees.setbirthday(line[3]);
                        employees.setaddress(line[4]);
                        employees.setphonenum(line[5]);
                        employees.setstatus(line[10]);
                        employees.setposition(line[11]);
                        employees.setsupervisor(line[12]);
                        employees.setbasic(line[13]);
                        employees.setriceall(line[14]);
                        employees.setphoneall(line[15]);
                        employees.setclotheall(line[16]);
                        employees.setsmrate(line[17]);
                        employees.sethourlyrate(line[18]);
                        break;
                    }
                }
                csvreader.close();

            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException | CsvValidationException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

            DeleteRecordFrame deleteframe = new DeleteRecordFrame(employees);
            deleteframe.setVisible(true);

            try {
                table1.setModel(employees.tableDetails(filename));
            } catch (IOException | CsvValidationException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        catch(ArrayIndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(this, "Select a row.", "Selection Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_DeleteRecord

    private void leavebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavebtnMouseClicked
        Employees employees = new Employees();

        try {

            employees.setemployeenum(table1.getModel().getValueAt(table1.getSelectedRow(), 0).toString());
            employees.setlastname(table1.getModel().getValueAt(table1.getSelectedRow(), 1).toString());
            employees.setfirstname(table1.getModel().getValueAt(table1.getSelectedRow(), 2).toString());

            LeaveFrame leaveframe = new LeaveFrame(employees);
            leaveframe.setVisible(true);

        }
        catch(ArrayIndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(this, "Select a row.", "Selection Error", JOptionPane.ERROR_MESSAGE);
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_leavebtnMouseClicked

    private void PaySlip(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaySlip
        Employees employees = new Employees();

        try{
            String en = table1.getModel().getValueAt(table1.getSelectedRow(), 0).toString();

            employees.setemployeenum(table1.getModel().getValueAt(table1.getSelectedRow(), 0).toString());
            employees.setlastname(table1.getModel().getValueAt(table1.getSelectedRow(), 1).toString());
            employees.setfirstname(table1.getModel().getValueAt(table1.getSelectedRow(), 2).toString());
            employees.setsss(table1.getModel().getValueAt(table1.getSelectedRow(),3).toString());
            employees.setphilhealth(table1.getModel().getValueAt(table1.getSelectedRow(), 4).toString());
            employees.settax(table1.getModel().getValueAt(table1.getSelectedRow(), 5).toString());
            employees.setpagibig(table1.getModel().getValueAt(table1.getSelectedRow(), 6).toString());

            String filename = "MotorPH Employee Data.csv";
            try {
                CSVReader csvreader = new CSVReader(new FileReader(filename));
                String[] line;

                while((line=csvreader.readNext())!=null){
                    if(line[0].equals(en)){
                        employees.setbirthday(line[3]);
                        employees.setaddress(line[4]);
                        employees.setphonenum(line[5]);
                        employees.setstatus(line[10]);
                        employees.setposition(line[11]);
                        employees.setsupervisor(line[12]);
                        employees.setbasic(line[13]);
                        employees.setriceall(line[14]);
                        employees.setphoneall(line[15]);
                        employees.setclotheall(line[16]);
                        employees.setsmrate(line[17]);
                        employees.sethourlyrate(line[18]);
                        break;
                    }
                }
                csvreader.close();

            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException | CsvValidationException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

            PayslipFrame payslipframe = new PayslipFrame(employees);
            payslipframe.setVisible(true);

        }
        catch(ArrayIndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(this, "Select a row.", "Selection Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_PaySlip

    private void AddEmployee(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddEmployee
        Employees employees = new Employees();
        AddEmployeeFrame addframe = new AddEmployeeFrame(employees);
        addframe.setVisible(true);
        String filename="MotorPH Employee Data.csv";

        try {
            table1.setModel(employees.tableDetails(filename));
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_AddEmployee

    private void AttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttendanceMouseClicked
        Employees employees = new Employees();

        try{
            String en = table1.getModel().getValueAt(table1.getSelectedRow(), 0).toString();

            employees.setemployeenum(table1.getModel().getValueAt(table1.getSelectedRow(), 0).toString());
            employees.setlastname(table1.getModel().getValueAt(table1.getSelectedRow(), 1).toString());
            employees.setfirstname(table1.getModel().getValueAt(table1.getSelectedRow(), 2).toString());
            employees.setsss(table1.getModel().getValueAt(table1.getSelectedRow(),3).toString());
            employees.setphilhealth(table1.getModel().getValueAt(table1.getSelectedRow(), 4).toString());
            employees.settax(table1.getModel().getValueAt(table1.getSelectedRow(), 5).toString());
            employees.setpagibig(table1.getModel().getValueAt(table1.getSelectedRow(), 6).toString());

            String filename = "MotorPH Employee Data.csv";
            try {
                CSVReader csvreader = new CSVReader(new FileReader(filename));
                String[] line;

                while((line=csvreader.readNext())!=null){
                    if(line[0].equals(en)){
                        employees.setbirthday(line[3]);
                        employees.setaddress(line[4]);
                        employees.setphonenum(line[5]);
                        employees.setstatus(line[10]);
                        employees.setposition(line[11]);
                        employees.setsupervisor(line[12]);
                        employees.setbasic(line[13]);
                        employees.setriceall(line[14]);
                        employees.setphoneall(line[15]);
                        employees.setclotheall(line[16]);
                        employees.setsmrate(line[17]);
                        employees.sethourlyrate(line[18]);
                        break;
                    }
                }
                csvreader.close();

            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException | CsvValidationException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

            ViewRecordFrame viewrecordframe = new ViewRecordFrame(employees);
            viewrecordframe.setVisible(true);

            try {
                table1.setModel(employees.tableDetails(filename));
            } catch (IOException | CsvValidationException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        catch(ArrayIndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(this, "Select a row.", "Selection Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_AttendanceMouseClicked

    private void viewbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewbtn1MouseClicked
        int selectedRow = table1.getSelectedRow();
    if (selectedRow != -1) {
        String employeeNum = table1.getModel().getValueAt(selectedRow, 0).toString(); // Assuming the first column is the employee number
        Employees employee = new Employees();
        
        try {
            // This is a hypothetical method. Replace it with your actual method to fetch employee details
            employee = employee.getEmployeeDetails(employeeNum); // Method to implement
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Failed to load employee details.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        ViewRecordFrame viewRecordFrame = new ViewRecordFrame(employee);
        viewRecordFrame.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Please select a row to view or update the record.", "No Selection", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_viewbtn1MouseClicked

    private void AttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttendanceActionPerformed
        Attendance attendance = new Attendance(); // Create an instance of the Attendance class
    attendance.setVisible(true); // Make the Attendance frame visible
    this.dispose(); // Close the current frame, optional depending on your requirements

    }//GEN-LAST:event_AttendanceActionPerformed

    private void viewbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewbtn1ActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletebtnActionPerformed

    private void payslipbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payslipbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payslipbtnActionPerformed

    private void leavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leavebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leavebtnActionPerformed

    private void exitbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtn1MouseClicked
        dispose();
        LogInFrame login = new LogInFrame();
        login.setVisible(true);
    }//GEN-LAST:event_exitbtn1MouseClicked

    private void exitbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitbtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainFrame().setVisible(true);
                } catch (IOException | CsvValidationException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Attendance;
    private javax.swing.JButton addbtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton exitbtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton leavebtn;
    private javax.swing.JButton payslipbtn;
    private javax.swing.JTable table1;
    private javax.swing.JButton viewbtn1;
    // End of variables declaration//GEN-END:variables
}
